version: '3.8'

services:
  nginx:
    image: nginx:stable-alpine3.20-perl
    ports:
      - "80:80" 
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - app-network
    depends_on:
      - frontend
      - backend


  frontend:
    image: fatemzahra/frontend:1.0
    networks:
      - app-network
    environment:
      - REACT_APP_BACKEND_URL=http://backend.local
    depends_on:
      - backend
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 256M
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s

  backend:
    image: fatemzahra/backend:1.0
    networks:
      - app-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/studenttrack
      - SPRING_DATASOURCE_USERNAME=studentadmin
      - SPRING_DATASOURCE_PASSWORD=adminpassword
    depends_on:
      - db
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 256M
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s

  db:
    image: mysql:8.0.40-debian
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: studenttrack
      MYSQL_USER: studentadmin
      MYSQL_PASSWORD: adminpassword
    ports:
      - "3306:3306"
    networks:
      - app-network
    volumes:
      - db_data:/var/lib/mysql
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.5"
          memory: 1G
        reservations:
          cpus: "0.25"
          memory: 512M
      restart_policy:
        condition: on-failure

volumes:
  db_data:
    driver: local


networks:
  app-network:
    driver: overlay
