apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: exam
data:
  SPRING_APPLICATION_NAME: backend
  SPRING_JPA_HIBERNATE_DDL_AUTO: update
  SPRING_JPA_SHOW_SQL: "true"
  SPRING_JACKSON_STREAM_WRITE_CONSTRAINTS_MAX_NESTING_DEPTH: "2000"
  SPRING_MVC_CONTENTNEGOTIATION_FAVOR_PARAMETER: "true"
  SPRING_MVC_CONTENTNEGOTIATION_MEDIA_TYPES_JSON: application/json
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: health
  MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED: "true"

---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: exam
type: Opaque
data:
  SPRING_DATASOURCE_URL: amRiYzpteXNxbDovL215c3FsOjMzMDYvc3R1ZGVudHRyYWNr
  SPRING_DATASOURCE_USERNAME: c3R1ZGVudGFkbWlu
  SPRING_DATASOURCE_PASSWORD: YWRtaW5wYXNzd29yZA==

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: exam
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: fatemzahra/backend:1.0
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secret
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"


---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: exam
spec:
  selector:
    app: backend
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080


