apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-limits
  namespace: exam
spec:
  hard:
    pods: "10" 
    requests.cpu: "3"
    requests.memory: 4Gi
    limits.cpu: "6"
    limits.memory: 6Gi
