apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-database
spec:
  type: NodePort
  ports:
  - port: 3306
    targetPort: 3306
    nodePort: 30082
  selector:
    app: {{ .Chart.Name }}
    component: database
