apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-database
  labels:
    app: {{ .Chart.Name }}
    component: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      component: database
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        component: database
    spec:
      containers:
      - name: database
        image: "{{ .Values.database.image.repository }}:{{ .Values.database.image.tag }}"
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "{{ .Values.database.environment.MYSQL_ROOT_PASSWORD }}"
        - name: MYSQL_DATABASE
          value: "{{ .Values.database.environment.MYSQL_DATABASE }}"
        - name: MYSQL_USER
          value: "{{ .Values.database.environment.MYSQL_USER }}"
        - name: MYSQL_PASSWORD
          value: "{{ .Values.database.environment.MYSQL_PASSWORD }}"
        ports:
        - containerPort: 3306
        resources:
          limits:
            cpu: {{ .Values.database.resources.limits.cpu }}
            memory: {{ .Values.database.resources.limits.memory }}
          requests:
            cpu: {{ .Values.database.resources.reservations.cpu }}
            memory: {{ .Values.database.resources.reservations.memory }}
        volumeMounts:
        - name: db-data
          mountPath: /var/lib/mysql
      volumes:  
      - name: db-data
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-db-pvc
